### PR TITLE
Send x-restate-id header back on each request

### LINKED ISSUE #1258: [Design] Add invocation ID to all response headers
Whether an invocation succeeds or fails, having the invocation id in the response header enable users to investigate issue, or re-attach to the invocation if a transient error was returned (depends on #1257)

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #1258

I'm gonna use this header in the java sdk to remove the parsing of the json object for the /send requests.

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
See https://github.com/restatedev/sdk-java/pull/328

File: crates/ingress-http/src/handler/responses.rs [hunk 1]
```diff
@@ -14,15 +14,18 @@ use bytes::Bytes;
...
 use http_body_util::Full;
 use restate_schema_api::invocation_target::InvocationTargetMetadata;
+use restate_types::identifiers::InvocationId;
 use restate_types::ingress::IngressResponseResult;
 use restate_types::invocation::InvocationTarget;
 use tracing::{info, trace};
 
-const IDEMPOTENCY_EXPIRES: HeaderName = HeaderName::from_static("idempotency-expires");
+pub(crate) const IDEMPOTENCY_EXPIRES: HeaderName = HeaderName::from_static("idempotency-expires");
+pub(crate) const X_RESTATE_ID: HeaderName = HeaderName::from_static("x-restate-id");
```
Comment (tillrohrmann) [inline crates/ingress-http/src/handler/responses.rs:23]: Maybe add a comment explaining what the expected value should be (stringified representation of InvocationId, I assume).

**Review by tillrohrmann — APPROVED** [review]
LGTM. +1 for merging.
