### PR TITLE
HTTP 1.1 now works with ALPN

### LINKED ISSUE #1899: Service endpoint using HTTP 1.1 with TLS
HTTP 1.1 doesn't work with TLS/ALPN.

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #1899

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Tested in a bunch of setups, including using `wrangler dev` and using `shuttle.rs`, and it works fine. Let's now wait for the CI judgement.

**Review by tillrohrmann — COMMENTED** [review]
Thanks for creating this PR @slinkydeveloper. I faintly remember that there was a reason why @jackkleeman introduced two clients. I think it was because if the connection is unencrypted then the ALPN client would default to HTTP1.1 is not supported by our node services. Is this no longer a problem?

File: crates/service-client/src/http.rs [hunk 1]
```diff
@@ -153,12 +141,7 @@ impl HttpClient {
             Err(err) => return future::ready(Err(err.into())).right_future(),
         };
 
-        let client = match request.version() {
-            Version::HTTP_2 => &self.h2_client,
-            _ => &self.alpn_client,
-        };
-
-        let fut = client.request(request);
+        let fut = self.alpn_client.request(request);
```
[the remark this answers is not in the document]
Comment (slinkydeveloper) [reply crates/service-client/src/http.rs:144]: >  So if the connection is unencrypted, the client won't default to HTTP1.1?

You got there before CI. Will make it working...

File: crates/service-client/src/http.rs [hunk 2]
```diff
@@ -74,23 +73,28 @@ impl HttpClient {
             .with_native_roots()
             .expect("Can build native roots")
             .https_or_http()
+            .enable_http1()
```
Comment (tillrohrmann) [inline crates/service-client/src/http.rs:76]: Just to be clear, for fixing the actual problem this is the only required change, right? Everything else is just massaging the existing code in different form?

File: crates/service-client/src/http.rs [hunk 3]
```diff
@@ -153,13 +159,16 @@ impl HttpClient {
...
 
-        let client = match request.version() {
-            Version::HTTP_2 => &self.h2_client,
-            _ => &self.alpn_client,
+        let fut = match (
+            request.version(),
+            request.uri().scheme().expect("URI should be absolute"),
+        ) {
+            (Version::HTTP_2, scheme) if scheme == &Scheme::HTTP => {
+                self.h2c_prior_knowledge_client.request(request)
```
Comment (tillrohrmann) [inline crates/service-client/src/http.rs:167]: Why can't we always use `h2c_prior_knowledge_client` if the version is `HTTP_2`?

**Review by tillrohrmann — COMMENTED** [review]
Thanks for updating the PR @slinkydeveloper. I had a last clarifying question regarding what is required and what's a clean up of this PR.

File: crates/service-client/src/http.rs (hunk 3 above)
Comment (slinkydeveloper) [reply crates/service-client/src/http.rs:167]: There's no need to create two https clients, we just use one here.

I think there's something here with the fact that we should work on our own pooling system in future, that among the other problems, can address those issues.

File: crates/service-client/src/http.rs (hunk 2 above)
Comment (slinkydeveloper) [reply crates/service-client/src/http.rs:76]: It's a mix of this change and the change below where in case of HTTPs we just let ALPN rule the version.

File: crates/service-client/src/http.rs (hunk 3 above)
Comment (tillrohrmann) [reply crates/service-client/src/http.rs:167]: Is this strictly required?

Comment (slinkydeveloper) [reply crates/service-client/src/http.rs:167]: it is required because of this change: https://github.com/restatedev/restate/pull/1900/files#diff-dcf1a0303314188fa354df1a0a0c2e4df9345d7e4911707b7042cfe6ae48f1c8R75

Comment (tillrohrmann) [reply crates/service-client/src/http.rs:167]: Ah ok, I think I know understand. Thanks for the clarification.

So before, we were only using the ALPN enabled client if the user forced the usage of `HTTP1.1`, right? So when running on a server with https and `HTTP1.1` it wouldn't have worked w/o the explicit forcing. Now when encountering https, we'll always use the ALPN enabled client. Consequently, users will only have to force the usage of `HTTP1.1` if they are running a service on an http server w/o TLS using HTTP1.1, right?

**Review by tillrohrmann — APPROVED** [review]
Thanks for your patience with me. It took me a bit longer to understand the problem of the previous version. The changes look good to. +1 for merging.
