### PR TITLE
Fix issue with submit notification for virtual objects

### LINKED ISSUE #1535: Swallowing submit notification when enqueuing into the inbox
We seem to not send submit notifications for invocation that get enqueued in the inbox. This is visible when running the verification test with more than 1 concurrent test. I think this problem was introduced with #1503.

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #1535

### CODE REVIEW

File: crates/worker/src/partition/state_machine/mod.rs [hunk 1]
```diff
@@ -1262,6 +1263,125 @@ mod tests {
...
+                            },
+                        }
+                    ))))
+                )
+            );
+            // Invocation is inboxed
+            assert_that!(
+                state_machine
+                    .rocksdb_storage
+                    .transaction()
```
Comment (tillrohrmann) [inline crates/worker/src/partition/state_machine/mod.rs:1331]: nit: You probably don't need a transaction here.

**Review by tillrohrmann — APPROVED** [review]
Thanks for fixing the issue so quickly @slinkydeveloper. LGTM. +1 for merging.

File: crates/worker/src/partition/state_machine/mod.rs (hunk 1 above)
Comment (slinkydeveloper) [reply crates/worker/src/partition/state_machine/mod.rs:1331]: we need it because the inbox table is not split.
