### PR TITLE
Let MultiplexedInvokerStatusReader share state

### LINKED ISSUE #1961: sys_invocation_state cannot be read
The `sys_invocation_state` table can no longer be read. It looks that this is a regression compared to version 1.0. I suspect that the `MultiplexedInvokerStatusReader` is shared between components w/o having properly shared state.

### PR DESCRIPTION
**Pull request by tillrohrmann**
The MultiplexedInvokerStatusReader now shares the ChannelStatusReader via an Arc<Mutex<>>.

This fixes #1961.

### CODE REVIEW

File: crates/worker/src/partition_processor_manager.rs [hunk 1]
```diff
@@ -242,14 +243,16 @@ impl PartitionProcessorHandle {
...
 #[derive(Debug, Clone, Default)]
 pub struct MultiplexedInvokerStatusReader {
-    readers: Vec<(RangeInclusive<PartitionKey>, ChannelStatusReader)>,
+    readers: Arc<Mutex<ChannelStatusReaderList>>,
 }
 
 impl MultiplexedInvokerStatusReader {
     fn push(&mut self, key_range: RangeInclusive<PartitionKey>, reader: ChannelStatusReader) {
-        self.readers.push((key_range, reader));
+        self.readers.lock().unwrap().push((key_range, reader));
```
Comment (muhamadazmy) [inline crates/worker/src/partition_processor_manager.rs:255]: I was wondering if a a RwLock would fit better here since I noticed this push happens only during starting of a partition processor which not frequent.

**Review by muhamadazmy — APPROVED** [review]
LGTM but I left one comment

File: crates/worker/src/partition_processor_manager.rs (hunk 1 above)
Comment (tillrohrmann) [reply crates/worker/src/partition_processor_manager.rs:255]: I think you are right. Will change it.
