### PR TITLE
Leave member state when removing yourself from Raft configuration

### LINKED ISSUE #3204: Flaky `restate-server::raft_metadata_cluster raft_metadata_cluster_reconfiguration`
Got this when running `just fmt verify` locally

```
        FAIL [  35.584s] restate-server::raft_metadata_cluster raft_metadata_cluster_reconfiguration
──── STDOUT:             restate-server::raft_metadata_cluster raft_metadata_cluster_reconfiguration

running 1 test
test raft_metadata_cluster_reconfiguration ... 2025-04-30T07:21:38.599686Z  INFO restate_local_cluster_runner::cluster: Starting cluster raft_metadata_cluster_reconfiguration in /tmp/.tmp55axHj
2025-04-30T07:21:38.607447Z  INFO restate_local_cluster_runner::node: Started node node-1 in /tmp/.tmp55axHj/node-1 (pid 74223) node_address=unix:/tmp/.tmp55axHj/node-1/node.sock admin_address=127.0.0.1:12253 ingress_address=None
2025-04-30T07:21:38.607505Z  INFO restate_local_cluster_runner::node: To connect to node node-1 using restate CLI:
export RESTATE_ADMIN_URL=http://127.0.0.1:12253
2025-04-30T07:21:38.618677Z  INFO restate_local_cluster_runner::node: Started node node-2 in /tmp/.tmp55axHj/node-2 (pid 74225) node_address=unix:/tmp/.tmp55axHj/node-2/node.sock admin_address=127.0.0.1:11715 ingress_address=None
2025-04-30T07:21:38.618728Z  INFO restate_local_cluster_runner::node: To connect to node node-2 using restate CLI:
export RESTATE_ADMIN_URL=http://127.0.0.1:11715
2025-04-30T07:21:38.628406Z  INFO restate_local_cluster_runner::node: Started node node-3 in /tmp/.tmp55axHj/node-3 (pid 74231) node_address=unix:/tmp/.tmp55axHj/node-3/node.sock admin_address=127.0.0.1:18756 ingress_address=None
2025-04-30T07:21:38.628458Z  INFO restate_local_cluster_runner::node: To connect to node node-3 using restate CLI:
export RESTATE_ADMIN_URL=http://127.0.0.1:18756
2025-04-30T07:21:39.736547Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:39.764301Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:40.313113Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 4 attempts
2025-04-30T07:21:40.536301Z  INFO restate_local_cluster_runner::node: Node node-1 Admin check is healthy after 5 attempts
2025-04-30T07:21:40.536448Z  INFO restate_local_cluster_runner::node: Node node-2 Admin check is healthy after 5 attempts
2025-04-30T07:21:40.538801Z  INFO restate_local_cluster_runner::node: Node node-3 Admin check is healthy after 5 attempts
2025-04-30T07:21:40.568223Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:40.695960Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:40.707144Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:40.724962Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:40.753641Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:41.088683Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.132976Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.186482Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.228218Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:41.493191Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.565505Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.574411Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.626887Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:41.778068Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.795696Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.884772Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:41.931863Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:42.299726Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.326485Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.343073Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.426836Z  INFO raft_metadata_cluster: Add node N3 to the metadata cluster
2025-04-30T07:21:42.680356Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.680590Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.696765Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.732794Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:42.834280Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.834821Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.855652Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:42.872995Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:43.044967Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.057600Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.068290Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.089984Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:43.172125Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.196165Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.202242Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.228027Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:43.284433Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.287686Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.310595Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.351847Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:43.478614Z  INFO raft_metadata_cluster: Add node N3 to the metadata cluster
2025-04-30T07:21:43.870085Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.920672Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:43.921906Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:44.030640Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:44.284756Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:44.311701Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:44.374223Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:44.560289Z  INFO raft_metadata_cluster: Remove node N1 from the metadata cluster at leader N1
2025-04-30T07:21:45.693933Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:45.695727Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:45.903131Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 4 attempts
2025-04-30T07:21:46.050290Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:46.179573Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:46.330395Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:46.499994Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:46.692521Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:46.857496Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:46.968735Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:47.138220Z  INFO raft_metadata_cluster: Add node N1 to the metadata cluster
2025-04-30T07:21:47.715939Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 2 attempts
2025-04-30T07:21:47.741111Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 2 attempts
2025-04-30T07:21:47.751426Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 2 attempts
2025-04-30T07:21:47.792168Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N3
2025-04-30T07:21:47.937191Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:47.938285Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:47.980111Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:47.996339Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N3
2025-04-30T07:21:49.055810Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:49.092654Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:49.122176Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:49.167970Z  INFO raft_metadata_cluster: Add node N3 to the metadata cluster
2025-04-30T07:21:49.405217Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.438373Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.463733Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.517633Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N1
2025-04-30T07:21:49.613238Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.649690Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.671220Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.699269Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:49.871874Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.920147Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.935844Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:49.970773Z  INFO raft_metadata_cluster: Add node N3 to the metadata cluster
2025-04-30T07:21:50.090109Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.090263Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.090370Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.125721Z  INFO raft_metadata_cluster: Remove node N2 from the metadata cluster at leader N1
2025-04-30T07:21:50.209781Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.231749Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.249400Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:50.285306Z  INFO raft_metadata_cluster: Remove node N1 from the metadata cluster at leader N1
2025-04-30T07:21:51.284377Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:51.321323Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:51.389338Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 3 attempts
2025-04-30T07:21:51.483809Z  INFO raft_metadata_cluster: Add node N2 to the metadata cluster
2025-04-30T07:21:51.603736Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:51.624487Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:51.739463Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:21:51.812426Z  INFO raft_metadata_cluster: Remove node N3 from the metadata cluster at leader N3
2025-04-30T07:21:59.995062Z  INFO raft_metadata_cluster: Add node N3 to the metadata cluster
2025-04-30T07:22:04.160905Z  INFO restate_local_cluster_runner::node: Node node-2 Admin check is healthy after 1 attempts
2025-04-30T07:22:04.166081Z  INFO restate_local_cluster_runner::node: Node node-1 Admin check is healthy after 1 attempts
2025-04-30T07:22:04.196372Z  INFO restate_local_cluster_runner::node: Node node-2 MetadataServer check is healthy after 1 attempts
2025-04-30T07:22:04.200018Z  INFO restate_local_cluster_runner::node: Node node-1 MetadataServer check is healthy after 1 attempts
2025-04-30T07:22:04.204169Z  INFO restate_local_cluster_runner::node: Node node-3 MetadataServer check is healthy after 1 attempts
2025-04-30T07:22:12.639992Z  INFO restate_local_cluster_runner::node: Node node-3 exited with signal: 6 (SIGABRT) (core dumped)
2025-04-30T07:22:14.140731Z ERROR restate_local_cluster_runner::node: Timed out waiting for check Admin on node node-3 to be active. Log tail:

NODE LOG node-3:              at /home/slinkydeveloper/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
NODE LOG node-3:   80: tokio::runtime::task::harness::poll_future
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
NODE LOG node-3:   81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
NODE LOG node-3:   82: tokio::runtime::task::harness::Harness<T,S>::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:15
NODE LOG node-3:   83: tokio::runtime::task::raw::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:271:5
NODE LOG node-3:   84: tokio::runtime::task::raw::RawTask::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
NODE LOG node-3:   85: tokio::runtime::task::UnownedTask<S>::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:500:9
NODE LOG node-3:   86: tokio::runtime::blocking::pool::Task::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:161:9
NODE LOG node-3:   87: tokio::runtime::blocking::pool::Inner::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:511:17
NODE LOG node-3:   88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:469:13
NODE LOG node-3: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
                
2025-04-30T07:22:14.141874Z  WARN restate_local_cluster_runner::node: Node node-1 (pid 74223) dropped without explicit shutdown
2025-04-30T07:22:14.142896Z  WARN restate_local_cluster_runner::node: Node node-2 (pid 74225) dropped without explicit shutdown
2025-04-30T07:22:14.143452Z  WARN restate_local_cluster_runner::node: Node node-3 (pid 74231) dropped without explicit shutdown
2025-04-30T07:22:14.144207Z  INFO shutdown_node{reason="completed"}: restate_core::task_center: ** Shutdown requested reason=completed
2025-04-30T07:22:14.144311Z  INFO shutdown_node{reason="completed"}: restate_core::task_center: ** Shutdown completed in 110.188µs
FAILED

failures:

failures:
    raft_metadata_cluster_reconfiguration

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 35.55s

──── STDERR:             restate-server::raft_metadata_cluster raft_metadata_cluster_reconfiguration
!!!! Running with test-util enabled !!!!
Error: Timed out waiting for check Admin on node node-3 to be active. Log tail:

NODE LOG node-3:              at /home/slinkydeveloper/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
NODE LOG node-3:   80: tokio::runtime::task::harness::poll_future
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
NODE LOG node-3:   81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
NODE LOG node-3:   82: tokio::runtime::task::harness::Harness<T,S>::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:15
NODE LOG node-3:   83: tokio::runtime::task::raw::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:271:5
NODE LOG node-3:   84: tokio::runtime::task::raw::RawTask::poll
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
NODE LOG node-3:   85: tokio::runtime::task::UnownedTask<S>::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:500:9
NODE LOG node-3:   86: tokio::runtime::blocking::pool::Task::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:161:9
NODE LOG node-3:   87: tokio::runtime::blocking::pool::Inner::run
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:511:17
NODE LOG node-3:   88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
NODE LOG node-3:              at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:469:13
NODE LOG node-3: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
                


  Cancelling due to test failure: 2 tests still running
```

### PR DESCRIPTION
**Pull request by tillrohrmann**
Instead of waiting only for the NodesConfiguration to tell us when we switched from Member to Standby state, this commit directly reacts to a configuration change where we removed ourselves. Otherwise, we might still process responses from other nodes because updating of the NodesConfiguration in the Metadata happens asynchronously from the KvMemoryStorage. Processing messages after we have removed ourselves can result in panics from the Raft library which doesn't expect this to happen.

This fixes #3204.

### CODE REVIEW

File: crates/metadata-server/src/raft/server.rs [hunk 1]
```diff
@@ -764,13 +766,9 @@ impl Member {
...
         loop {
             tokio::select! {
-                biased;
-                // It is important to always check for nodes config changes because that's our
-                // mechanism to remove ourselves from the cluster if we are supposed to leave.
-                // Otherwise, we might process a Raft response message which causes Raft to panic,
-                // because we removed ourselves from it.
                 Ok(()) = nodes_config_watch.changed() => {
-                    if self.should_leave() {
+                    let nodes_config = Metadata::with_current(|m| m.nodes_config_ref());
```
Comment (AhmedSoliman) [inline crates/metadata-server/src/raft/server.rs:770]: tip: actor loops like those are an excellent spot for using Live's live_load() for fast config access, then you can pass down the reference as needed.

**Review by AhmedSoliman — APPROVED** [review]
Thanks for the quick fix @tillrohrmann

File: crates/metadata-server/src/raft/server.rs (hunk 1 above)
Comment (tillrohrmann) [reply crates/metadata-server/src/raft/server.rs:770]: Good point. Will update it.
