### PR TITLE
[connection-pool] Cap per-connection max-concurrent-streams

### LINKED ISSUE #4650: AuthorityPool panics with attempt to add with overflow
While debugging another panic, I ran into the `AuthorityPool` panicking when running the e2e verification tests with vqueues enabled.

```
026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] [Some("rt:pp-0")]  PANIC!!!
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] panicked at crates/service-client/src/pool/authority.rs:206:17:
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] attempt to add with overflow
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3]
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3]
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] thread 'rt:pp-0' (163) panicked at crates/service-client/src/pool/authority.rs:206:17:
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] attempt to add with overflow
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] stack backtrace:
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 0:     0xaaaaf30b28b8 - std[cc6062c208ed37d1]::backtrace_rs::backtrace::libunwind::trace
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 1:     0xaaaaf30b28b8 - std[cc6062c208ed37d1]::backtrace_rs::backtrace::trace_unsynchronized::<std[cc6062c208ed37d1]::sys::backtrace::_print_fmt::{closure#1}>
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 2:     0xaaaaf30b28b8 - std[cc6062c208ed37d1]::sys::backtrace::_print_fmt
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/backtrace.rs:74:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 3:     0xaaaaf30b28b8 - <<std[cc6062c208ed37d1]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[4e11ee24e72d71de]::fmt::Display>::fmt
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/backtrace.rs:44:26
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 4:     0xaaaaf30cde7c - <core[4e11ee24e72d71de]::fmt::rt::Argument>::fmt
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/fmt/rt.rs:152:76
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 5:     0xaaaaf30cde7c - core[4e11ee24e72d71de]::fmt::write
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/fmt/mod.rs:1686:22
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 6:     0xaaaaf30ba790 - std[cc6062c208ed37d1]::io::default_write_fmt::<std[cc6062c208ed37d1]::sys::stdio::unix::Stderr>
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/io/mod.rs:639:11
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 7:     0xaaaaf30ba790 - <std[cc6062c208ed37d1]::sys::stdio::unix::Stderr as std[cc6062c208ed37d1]::io::Write>::write_fmt
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/io/mod.rs:1994:13
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 8:     0xaaaaf309342c - <std[cc6062c208ed37d1]::sys::backtrace::BacktraceLock>::print
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/backtrace.rs:47:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 9:     0xaaaaf309342c - std[cc6062c208ed37d1]::panicking::default_hook::{closure#0}
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:292:27
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 10:     0xaaaaf30a950c - std[cc6062c208ed37d1]::panicking::default_hook
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:319:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 11:     0xaaaae918c150 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hca98709a094ba73b
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/alloc/src/boxed.rs:2254:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 12:     0xaaaae9a250c4 - restate_server::main::{{closure}}::{{closure}}::h358d8c68ca02de4a
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/server/src/main.rs:233:17
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 13:     0xaaaaf30a96fc - <alloc[2d7e41dc5aa60128]::boxed::Box<dyn for<'a, 'b> core[4e11ee24e72d71de]::ops::function::Fn<(&'a std[cc6062c208ed37d1]::panic::PanicHookInfo<'b>,), Output = ()> + core[4e11ee24e72d71de]::marker::Sync + core[4e11ee24e72d71de]::marker::Send> as core[4e11ee24e72d71de]::ops::function::Fn<(&std[cc6062c208ed37d1]::panic::PanicHookInfo,)>>::call
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/alloc/src/boxed.rs:2254:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 14:     0xaaaaf30a96fc - std[cc6062c208ed37d1]::panicking::panic_with_hook
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:833:13
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 15:     0xaaaaf3093508 - std[cc6062c208ed37d1]::panicking::panic_handler::{closure#0}
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:691:13
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 16:     0xaaaaf308a0bc - std[cc6062c208ed37d1]::sys::backtrace::__rust_end_short_backtrace::<std[cc6062c208ed37d1]::panicking::panic_handler::{closure#0}, !>
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/backtrace.rs:182:18
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 17:     0xaaaaf30946b4 - __rustc[b7974e8690430dd9]::rust_begin_unwind
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:689:5
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 18:     0xaaaae8deaaf0 - core[4e11ee24e72d71de]::panicking::panic_fmt
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/panicking.rs:80:14
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 19:     0xaaaae8deac14 - core[4e11ee24e72d71de]::panicking::panic_const::panic_const_add_overflow
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/panicking.rs:175:17
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 20:     0xaaaaeb56d728 - restate_service_client::pool::authority::AuthorityPool<C>::poll_ready::h882a1d6cc9b9fd25
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/crates/service-client/src/pool/authority.rs:206:17
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 21:     0xaaaaeb4e68e8 - restate_service_client::pool::Pool<C>::request::{{closure}}::{{closure}}::h21947d86e728f2c5
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/crates/service-client/src/pool/mod.rs:115:45
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 22:     0xaaaaeb4c3828 - <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h19400e947d4ea932
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.32/src/future/poll_fn.rs:56:9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 23:     0xaaaaeb4e6458 - restate_service_client::pool::Pool<C>::request::{{closure}}::h0ebc43abe0653407
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/crates/service-client/src/pool/mod.rs:115:61
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 24:     0xaaaaeb5c9598 - <restate_service_client::http::ResponseMapper<F,B,E> as core::future::future::Future>::poll::h2a638b735ca551fb
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/crates/service-client/src/http.rs:279:48
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 25:     0xaaaaeb57ef04 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h2aa347b772a99472
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.32/src/future/either.rs:109:35
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 26:     0xaaaaeb57f160 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::hb10a1cead830d1f9
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.32/src/future/either.rs:108:34
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 27:     0xaaaaeb4cc8d0 - restate_service_client::ServiceClient::call::{{closure}}::h0b4fa9176bfa59f3
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /restate/crates/service-client/src/lib.rs:150:26
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] 28:     0xaaaaeb57ef90 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h4292ac1ba3550133
2026-04-24T20:58:27.382Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.32/src/future/either.rs:108:34
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 29:     0xaaaaeb57f0ec - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h72598c347e61ac6b
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.32/src/future/either.rs:108:34
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 30:     0xaaaaeb568678 - <core::pin::Pin<P> as core::future::future::Future>::poll::hdda1a5b3becd9ee2
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/future/future.rs:133:9
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 31:     0xaaaaeb554e60 - <tokio::runtime::task::trace::Root<T> as core::future::future::Future>::poll::h996434efcbe2e09c
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/trace/mod.rs:369:25
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 32:     0xaaaaeb51e340 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::haf3208ceea2269a2
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tracing-0.1.44/src/instrument.rs:321:15
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 33:     0xaaaaeb518a0c - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h8d014f3fc400d52f
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/core.rs:375:24
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 34:     0xaaaaeb517d98 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hae310a622cbb5d9c
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/loom/std/unsafe_cell.rs:16:9
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 35:     0xaaaaeb517d98 - tokio::runtime::task::core::Core<T,S>::poll::h36885cff018ef369
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/core.rs:364:30
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 36:     0xaaaaeb5b2a40 - tokio::runtime::task::harness::poll_future::{{closure}}::h279a22172b68ae4c
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/harness.rs:535:30
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 37:     0xaaaaeb4bfca8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2f0ac6b566048dfe
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/panic/unwind_safe.rs:274:9
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 38:     0xaaaaeb5ac314 - std::panicking::catch_unwind::do_call::h376ebf7a16009955
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:581:40
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 39:     0xaaaaeb4d3f98 - __rust_try
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 40:     0xaaaaeb4cfc88 - std::panicking::catch_unwind::hbf4b0834cd8f4431
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:544:19
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 41:     0xaaaaeb4cfc88 - std::panic::catch_unwind::he02ff6e03933822a
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panic.rs:359:14
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 42:     0xaaaaeb5b220c - tokio::runtime::task::harness::poll_future::hb806b4b6951c0603
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/harness.rs:523:18
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 43:     0xaaaaeb5b4260 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hd18b361d4a9e35fa
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/harness.rs:210:27
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 44:     0xaaaaeb5b66d4 - tokio::runtime::task::harness::Harness<T,S>::poll::hbf88b8a774c4b574
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/harness.rs:155:20
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 45:     0xaaaaeb5a6c08 - tokio::runtime::task::raw::poll::h85f8a1bfb432aa9f
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/raw.rs:337:13
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 46:     0xaaaaf2b4e15c - tokio::runtime::task::raw::RawTask::poll::h6b2e37d4ce917943
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/raw.rs:267:18
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 47:     0xaaaaf2b0f674 - tokio::runtime::task::LocalNotified<S>::run::hb1f0b00f4038bc34
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/task/mod.rs:515:13
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 48:     0xaaaae8ec22f0 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::h867702b08d3e9299
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:825:30
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 49:     0xaaaae8ebe83c - tokio::task::coop::with_budget::h1034ca5729984401
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/task/coop/mod.rs:167:5
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 50:     0xaaaae8ebe83c - tokio::task::coop::budget::h7edc94cfe098c95f
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/task/coop/mod.rs:133:5
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 51:     0xaaaae8ebe83c - tokio::runtime::scheduler::current_thread::Context::run_task::{{closure}}::h5e8b1e9e0fd73848
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:373:43
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 52:     0xaaaae8ebdc04 - tokio::runtime::scheduler::current_thread::Context::enter::h7f9cc1669570b716
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:451:19
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 53:     0xaaaae8ebe51c - tokio::runtime::scheduler::current_thread::Context::run_task::hde5387585f0edbca
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:373:28
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 54:     0xaaaae8ec0b9c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::hb84b94882aad6182
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:821:43
2026-04-24T20:58:27.383Z testcontainers:containers [6f70444e35c3] 55:     0xaaaae8ebf7e8 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::h66eba5d53b7c4eb6
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:865:68
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 56:     0xaaaaea8e987c - tokio::runtime::context::scoped::Scoped<T>::set::hdcae05d6950b975a
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/context/scoped.rs:40:9
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 57:     0xaaaae9c4fa00 - tokio::runtime::context::set_scheduler::{{closure}}::h308a77a4ec6463b1
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/context.rs:181:38
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 58:     0xaaaaea47e528 - std::thread::local::LocalKey<T>::try_with::hf1e6490998e05122
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/thread/local.rs:513:12
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 59:     0xaaaaea42bebc - std::thread::local::LocalKey<T>::with::hd401c35ea8ff85a6
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/thread/local.rs:477:20
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 60:     0xaaaae9c4f8f0 - tokio::runtime::context::set_scheduler::ha3ddc0936aa2e291
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/context.rs:181:17
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 61:     0xaaaae8ebefc4 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::h111bc0abe8da5e0b
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:865:27
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 62:     0xaaaae8ebf860 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h4e2473c6c3dde2f6
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:765:24
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 63:     0xaaaae8ea3448 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}::h1caaea5b23eddf72
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:205:33
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 64:     0xaaaae93ca904 - tokio::runtime::context::runtime::enter_runtime::h9d126fb5b02ab661
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/context/runtime.rs:65:16
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 65:     0xaaaae8ea30e8 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h547c8ffc98df2a58
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/scheduler/current_thread/mod.rs:193:9
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 66:     0xaaaae9fddba8 - tokio::runtime::runtime::Runtime::block_on_inner::h168fd1b2dccbc66b
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/runtime.rs:371:52
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 67:     0xaaaae9fde5d0 - tokio::runtime::runtime::Runtime::block_on::h06de0972e64402da
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.52.1/src/runtime/runtime.rs:343:18
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 68:     0xaaaae91ec0cc - restate_core::task_center::TaskCenterInner::start_runtime::{{closure}}::h83cc95ab37e6b4de
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /restate/crates/core/src/task_center.rs:772:44
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 69:     0xaaaaea136654 - std::sys::backtrace::__rust_begin_short_backtrace::hfac548d5d20d550b
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/backtrace.rs:166:18
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 70:     0xaaaae9b96aa0 - std::thread::lifecycle::spawn_unchecked::{{closure}}::{{closure}}::h835c92a2599dcbed
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/thread/lifecycle.rs:91:13
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 71:     0xaaaae8e138a0 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h80b5d1ea0e7c3f04
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/panic/unwind_safe.rs:274:9
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 72:     0xaaaae9ba9a34 - std::panicking::catch_unwind::do_call::h7229a5b7cf08776c
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:581:40
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 73:     0xaaaae9cc7540 - __rust_try
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 74:     0xaaaae9b959e4 - std::panicking::catch_unwind::hea1ea3a98f6aaa16
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panicking.rs:544:19
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 75:     0xaaaae9b959e4 - std::panic::catch_unwind::ha995156fceb87d00
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/panic.rs:359:14
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 76:     0xaaaae9b959e4 - std::thread::lifecycle::spawn_unchecked::{{closure}}::h258da3bb6154862b
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/thread/lifecycle.rs:89:26
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 77:     0xaaaae9e8ea44 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h628326b8856e7228
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/core/src/ops/function.rs:250:5
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 78:     0xaaaaf30b1638 - <alloc[2d7e41dc5aa60128]::boxed::Box<dyn core[4e11ee24e72d71de]::ops::function::FnOnce<(), Output = ()> + core[4e11ee24e72d71de]::marker::Send> as core[4e11ee24e72d71de]::ops::function::FnOnce<()>>::call_once
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/alloc/src/boxed.rs:2240:9
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 79:     0xaaaaf30b1638 - <std[cc6062c208ed37d1]::sys::thread::unix::Thread>::new::thread_start
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library/std/src/sys/thread/unix.rs:118:17
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 80:     0xffff88195f38 - <unknown>
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 81:     0xffff881fdc2c - <unknown>
2026-04-24T20:58:27.384Z testcontainers:containers [6f70444e35c3] 82:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by muhamadazmy**
[connection-pool] Cap per-connection max-concurrent-streams

Summary:
Currently the per-connection concurrent-streams limit is whatever the peer
advertises in its SETTINGS frame, falling back to usize::MAX when no value is
sent. With an effectively unbounded limit, the pool's saturation threshold is
never crossed, so:

  * every request funnels through the first established connection,
  * the pool never opens additional connections, and
  * any load balancer in front of the deployment sees a single long-lived
    HTTP/2 connection and cannot spread requests across backends.

This change introduces `cap_max_send_streams` (default 128) and clamps the
effective per-connection limit to:

    min(peer.max_concurrent_streams, cap_max_send_streams)

That bound is low enough that connections saturate under realistic load,
which lets the existing saturation logic in `AuthorityPool` spawn new
connections, restoring fan-out across LB-balanced backends, including the
end-to-end HTTP/2 path.

Secondary cleanups in the same change:
  * `PoolConfig` is now `Copy` (all fields are stack-sized) and cloning the
    authority pool no longer allocates.
  * `ConnectionConfig` is built once per `AuthorityPool` instead of
    re-derived on every new connection.
  * Stream-count aggregation in the saturation check uses `saturating_add`.

Fixes #4650

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/4654).
* #4666
* __->__ #4654

### CODE REVIEW

File: crates/service-client/src/pool/config.rs [hunk 1]
```diff
@@ -43,8 +43,28 @@ pub struct PoolConfig {
...
+    /// We then clamp that effective limit to
+    /// `min(peer.max_concurrent_streams, cap_max_send_streams)` so the pool
+    /// keeps opening new connections instead of funneling every request through
+    /// a single one. Without this cap, a single connection can saturate its
+    /// flow-control window and interacts poorly with load balancers, especially
+    /// with end-to-end HTTP/2.
+    ///
+    /// Default: 128
+    #[builder(default = NonZeroUsize::new(128).unwrap())]
+    pub(crate) cap_max_send_streams: NonZeroUsize,
```
Comment (AhmedSoliman) [inline crates/service-client/src/pool/config.rs]: cap+max can be confusing in the same name. Would something like `streams_per_connection_limit` work?

Comment (muhamadazmy) [reply crates/service-client/src/pool/config.rs]: Sounds good to me. Will rename

File: crates/service-client/src/pool/config.rs [hunk 2]
```diff
@@ -43,8 +43,28 @@ pub struct PoolConfig {
...
+    ///
+    /// Default: 50
     #[builder(default = NonZeroU32::new(50).unwrap())]
     pub(crate) initial_max_send_streams: NonZeroU32,
+
+    /// Upper bound on the per-connection max-send-streams.
+    ///
+    /// Once the HTTP/2 Connection Preface completes, `initial_max_send_streams`
+    /// is replaced by the peer's `max_concurrent_streams` from its SETTINGS
+    /// frame, or by `usize::MAX` if the peer advertises no value.
```
Comment (tillrohrmann) [inline crates/service-client/src/pool/config.rs]: No need to go into the details that no advertised value will be interpreted as `usize::MAX`. I think we can say that after the preface completes, we take whatever the peer advertised but clamped to `streams_per_connection_limit`.

File: crates/service-client/src/pool/config.rs [hunk 3]
```diff
@@ -43,8 +43,28 @@ pub struct PoolConfig {
...
+    ///
+    /// We then clamp that effective limit to
+    /// `min(peer.max_concurrent_streams, streams_per_connection_limit)` so the pool
+    /// keeps opening new connections instead of funneling every request through
+    /// a single one. Without this cap, a single connection can saturate its
+    /// flow-control window and interacts poorly with load balancers, especially
+    /// with end-to-end HTTP/2.
```
Comment (tillrohrmann) [inline crates/service-client/src/pool/config.rs]: L4 load balancers don't work well, right? With L7 LBs stream on the same connection should be load balanced across the backends, right?

File: crates/service-client/src/pool/config.rs [hunk 4]
```diff
@@ -43,8 +43,28 @@ pub struct PoolConfig {
...
+    ///
+    /// Default: 128
```
Comment (tillrohrmann) [inline crates/service-client/src/pool/config.rs:61]: This is probably a magic number that we have guesstimated, right?

File: crates/service-client/src/pool/conn.rs [hunk 5]
```diff
@@ -885,6 +911,51 @@ mod test {
...
+                .build()
+                .unwrap(),
+        );
+
+        // First request triggers the handshake. Drop the body to release the permit.
+        drop(send_request(&mut connection).await);
+
+        // Second ready() hits the Connected arm which resizes the semaphore
+        // to min(cap=3, server=50)=3. Drop the body to release the permit.
+        drop(send_request(&mut connection).await);
```
Comment (tillrohrmann) [inline crates/service-client/src/pool/conn.rs]: Why wouldn't the first send_request set the max streams properly?

File: crates/types/src/config/http.rs [hunk 6]
```diff
@@ -62,6 +62,24 @@ pub struct HttpOptions {
...
+    /// Once the HTTP/2 Connection Preface completes, `initial_max_send_streams`
+    /// is replaced by the peer's `max_concurrent_streams` from its SETTINGS
+    /// frame, or by `usize::MAX` if the peer advertises no value.
+    ///
+    /// We then clamp that effective limit to
+    /// `min(peer.max_concurrent_streams, streams_per_connection_limit)` so the pool
+    /// keeps opening new connections instead of funneling every request through
+    /// a single one. Without this cap, a single connection can saturate its
+    /// flow-control window and interacts poorly with load balancers, especially
+    /// with end-to-end HTTP/2.
```
Comment (tillrohrmann) [inline crates/types/src/config/http.rs]: Same comments as for the `PoolConfig` apply here.

**Review by tillrohrmann — APPROVED** [review]
Thanks a lot for introducing the streams per connection limit @muhamadazmy. The changes look good to me. +1 for merging :-)

File: crates/service-client/src/pool/config.rs (hunk 3 above)
Comment (muhamadazmy) [reply crates/service-client/src/pool/config.rs]: Yes, indeed. I will update the comment to reflect that.

File: crates/service-client/src/pool/config.rs (hunk 4 above)
Comment (muhamadazmy) [reply crates/service-client/src/pool/config.rs:61]: it is a magic number. The idea is that it's better to keep this number small since we are not bound with fixed max number of connections. At the same time it's a little bit above the "common" max concurrent streams of `100`.

File: crates/service-client/src/pool/conn.rs (hunk 5 above)
Comment (muhamadazmy) [reply crates/service-client/src/pool/conn.rs]: SETTINGS frame is send from the remote peer asynchronously. Which means there is no guarantee that the `driving` request (the first one) will "observe" the advertised `max-concurrent-streams` and might still rely on the `initial_send_streams` settings on the client side.

What i think is missing here is that the `initial_send_streams` should be capped as well. Will update the PR to include that.
