### PR TITLE
Fix issue with incorrect command count

### LINKED ISSUE #3182: Journal commands size doesn't include input entry
Double check this, it might result in an incorrect retry status showing in UI

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #3182

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
FYI @nikrooz

File: crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs [hunk 1]
```diff
@@ -67,10 +68,13 @@ where
...
+                // Mutate the journal metadata commands
+                self.metadata.journal_metadata.commands = 1;
             } else {
                 // We're already in journal table v2, nothing to migrate!!!
             }
-        } else if self.journal_length >= 1 {
+        } else if self.metadata.journal_metadata.length >= 1 {
             // We can just check corruption here.
             // Length can be greater than 1 when we have either Completions (in the old table) or Notifications (in the new table).
             // Because of the different Awakeable id format, we cannot incur in the situation where we write to the old table for a Completion arrived before the pinned deployment.
```
Comment (tillrohrmann) [inline crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs:80]: Can the `debug_assert` become an `assert` in the line below? I think we should have these kind of checks also in release builds.

**Review by tillrohrmann — APPROVED** [review]
Thanks for fixing this bug @slinkydeveloper. LGTM. +1 for merging.
