### PR TITLE
Use the `VersionedValue` version in etcd metdata store

### LINKED ISSUE #2204: Etcd external metadata store assumes aligned versions which makes it broken
It seems that we are not aligning the etcd versions with our versions but use our versions for the conditional checks. This looks like it probably does not work properly in the general case. It should work if we always start with version 1 and don’t leave any gaps.

### PR DESCRIPTION
**Pull request by muhamadazmy**
Use the `VersionedValue` version in etcd metdata store

Summary:
Avoid etcd version misalignment with `VersionedValue` by storing the
version separately in its own key

Fixes #2204

### CODE REVIEW

File: crates/core/src/metadata_store/providers/etcd.rs [hunk 1]
```diff
@@ -106,69 +94,148 @@ impl EtcdMetadataStore {
...
+        ]);
 
         let response = client.txn(txn).await?;
 
         Ok(response.succeeded())
     }
+
+    fn version_key(key: &Bytes) -> Bytes {
+        let mut version_key = BytesMut::from_iter(key);
+        version_key.put(&b"::version"[..]);
```
Comment (tillrohrmann) [inline crates/core/src/metadata_store/providers/etcd.rs:191]: Preallocating the `BytesMut` might save us an reallocation when adding the `::version` suffix.

**Comment by muhamadazmy** [comment]
@tillrohrmann Thank you so much for your review ❤️. Yes, I tested it locally. I will merge after applying your comment 😊
