### PR TITLE
Don't panic if we cannot obtain connection attemp result

### LINKED ISSUE #2879: TaskHandle::is_finished == true does not mean that TaskHandle is Poll::Ready
During a verification run (https://github.com/restatedev/e2e-verification-runner/actions/runs/13742949412/job/38434376749#step:5:3082), a Restate server panicked here https://github.com/restatedev/restate/blob/41e606e6c2c6535134f0e7ee5d6bd70ce12b924a/crates/metadata-server/src/raft/network/networking.rs#L110. It seems that the assumption that if `TaskHandle::is_finished() == true`, then the `TaskHandle` is `Poll::Ready`, does not hold true.

What's the exact state of the system at the time of panicking, is unclear from the logs.

### PR DESCRIPTION
**Pull request by tillrohrmann**
For logging purposes we try to obtain the result of the connection attempt in a synchronous function if the connection attempt task has finished. Unfortunately, we cannot rely on TaskHandle::is_finished for task_handle.now_or_never() to always return Some(...). The problem is that the underlying Tokio JoinHandle participates in the cooperative task scheduling and if we ran out of budget, then it would return Poll::Pending. That's why we ignore the result in this case and continue.

This fixes #2879.

### CODE REVIEW

File: crates/metadata-server/src/raft/network/networking.rs [hunk 1]
```diff
@@ -103,23 +103,28 @@ where
...
         } else if let Some(address) = self.addresses.get(&target) {
-            if let Some(task_handle) = self.connection_attempts.remove(&target) {
-                if !task_handle.is_finished() {
+            if let Entry::Occupied(occupied) = self.connection_attempts.entry(target) {
+                if !occupied.get().is_finished() {
                     return Err(TrySendError::Connecting(message));
                 } else {
-                    match task_handle.now_or_never().expect("should be finished") {
-                        Ok(result) => match result {
+                    match occupied.remove().now_or_never() {
```
Comment (AhmedSoliman) [inline crates/metadata-server/src/raft/network/networking.rs:110]: you can also use `unconstrained()` but it's always safer to not panic anyway.

**Review by AhmedSoliman — APPROVED** [review]
LGTM assuming that the failing test is unrelated

File: crates/metadata-server/src/raft/network/networking.rs (hunk 1 above)
Comment (tillrohrmann) [reply crates/metadata-server/src/raft/network/networking.rs:110]: Good point. I'll remember it for the future :-)
