### PR TITLE
Fence retry timers in the invoker to avoid panics and incorrect state transitions

### LINKED ISSUE #4064: Invoker can panic if invocation was manually paused
@nikrooz ran into an invoker panic when doing the following:

> - Have a handler with a combinator for 3 ctx.runs, 2 will always fail (not terminal)  and the other takes very long time
> - In one stage that it was backing-off, I tried to `pause` the invocation
> - and then tried to `resume` it

```
[Some("rt:pp-8")]  PANIC!!!
panicked at crates/invoker-impl/src/invocation_state_machine.rs:404:9:
assertion failed: matches!(&self.invocation_state, AttemptState::WaitingRetry { .. })


thread 'rt:pp-8' (1478256) panicked at crates/invoker-impl/src/invocation_state_machine.rs:404:9:
assertion failed: matches!(&self.invocation_state, AttemptState::WaitingRetry { .. })
2025-11-25T15:58:43.850858Z ERROR tracing_panic
  A panic occurred
    panic.payload: "assertion failed: matches!(&self.invocation_state, AttemptState::WaitingRetry { .. })"
    panic.location: "crates/invoker-impl/src/invocation_state_machine.rs:404:9"
    panic.backtrace: disabled backtrace
    panic.note: "run with RUST_BACKTRACE=1 environment variable to display a backtrace"
on rt:pp-8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It seems that we are violating an invariant in the invoker where we expect it to be in the `AttemptState::WaitingRetry` state.

### PR DESCRIPTION
**Pull request by tillrohrmann**
This commit fixes #4064 by replacing the TimerQueue with tokio_util::DelayQueue for retry timer management in the invoker, and introducing a fencing mechanism to prevent stale timers from causing panics or incorrect state transitions.

Problem
-------
The invoker could experience panics and incorrect behavior when retry timers fired after the invocation state machine (ISM) had already transitioned to a different state. Orphaned timers from previous retry cycles could fire and trigger assertions or invalid state transitions.

Solution
--------
1. Replaced restate-timer-queue with tokio_util::DelayQueue: The new implementation uses DelayQueue which provides a Key for each inserted timer, enabling precise timer cancellation and identification.

2. Added timer fencing via RetryTimerKey: Each WaitingRetry state now stores the key of its associated retry timer. When a timer fires, the ISM verifies the key matches before reacting - stale timers are silently ignored.

3. Explicit timer cancellation: When an ISM transitions out of WaitingRetry state (via abort, pause, partition removal, or retry-now), the pending timer is explicitly cancelled using try_remove().

4. Refactored handle_task_error: The method now accepts a closure to register the timer, ensuring the timer key is captured at creation time and stored in the ISM state.

Key changes
-----------
- Removed restate-timer-queue dependency from restate-invoker-impl
- Added tokio-util with time feature for DelayQueue
- notify_retry_timer_fired() now takes a RetryTimerKey and validates it
- Added take_retry_timer_key() to retrieve the timer key from WaitingRetry state
- Periodic compaction of the DelayQueue every 10 seconds to reclaim memory
- Renamed OnTaskError::ScheduleRetry to OnTaskError::Retrying
- Updated all tests to use the new timer registration pattern

### CODE REVIEW

File: crates/invoker-impl/src/invocation_state_machine.rs [hunk 1]
```diff
@@ -129,15 +141,20 @@ enum AttemptState {
         using_deployment: Option<PinnedDeployment>,
         // If true, we need to notify the deployment id to the partition processor
         should_notify_pinned_deployment: bool,
+
+        // PhantomData to use the K type parameter
+        _marker: PhantomData<K>,
```
Comment (muhamadazmy) [inline crates/invoker-impl/src/invocation_state_machine.rs]: I don't believe this is needed since K is already used by the WaitingRetry variant

Comment (tillrohrmann) [reply crates/invoker-impl/src/invocation_state_machine.rs]: I think you are right. Thanks for catching it. Will fix it :-)
