### PR TITLE
Handle Invoker unexpected crashes

### LINKED ISSUE #4102: Prevent invoker from hanging when its task panics
In #4085, a bug caused the invoker task to panic. While the root cause of that panic has since been fixed, the incident showed that when the invoker task panics, the invoker can end up in an undefined state and silently hang, with no clear signal or recovery path.

### PR DESCRIPTION
**Pull request by muhamadazmy**
Handle Invoker unexpected crashes

Summary:
Gracefully handle invoker unexpected crashes by shutting down
the partition gracefully so it can be restarted cleanly

Fixes #4102

### CODE REVIEW

File: crates/worker/src/partition_processor_manager/spawn_processor_task.rs [hunk 1]
```diff
@@ -172,19 +174,40 @@ impl SpawnPartitionProcessorTask {
...
+                            warn!(
+                                partition_id = %partition.partition_id,
+                                "Invoker process stopped unexpectedly"
+                            );
+
+                            // Cancel the current task then run the PP to completion
+                            // for a clean PP shutdown
+                            let task_cancellation_token = cancellation_token();
+                            task_cancellation_token.cancel();
+                            run_fut.await?;
```
Comment (tillrohrmann) [inline crates/worker/src/partition_processor_manager/spawn_processor_task.rs]: Throwing a possible error here could mask the actual problem which was originally the `InvokerStoppedUnexpectedly`. Maybe logging it is enough.

File: crates/worker/src/partition_processor_manager/spawn_processor_task.rs [hunk 2]
```diff
@@ -172,19 +174,40 @@ impl SpawnPartitionProcessorTask {
...
+                    tokio::select! {
+                        result = &mut run_fut => {
+                            let _ = invoker.cancel_and_wait().await;
+                            info!(
+                                partition_id = %partition.partition_id,
+                                "Partition processor stopped"
+                            );
+                            result
+                        }
+                        _ = &mut invoker => {
```
Comment (tillrohrmann) [inline crates/worker/src/partition_processor_manager/spawn_processor_task.rs:196]: Potential follow-up: It could be nicer to propagate the `JoinError` from the `TaskGuard`. Otherwise the panic might be burried deep down in the logs and we cannot propagate the original cause for the invoker failure.
