### PR TITLE
[LogController] debounce on failure to avoid busy loops

### LINKED ISSUE #2079: Debounce failed log sealings/logs writes
See https://github.com/restatedev/restate/pull/2053/files#diff-5145e40acf9b30f1bef7be5855117b68387f1805c73fed11c9014d261ae8e943R615 and https://github.com/restatedev/restate/pull/2053/files#diff-5145e40acf9b30f1bef7be5855117b68387f1805c73fed11c9014d261ae8e943R639.

### PR DESCRIPTION
**Pull request by muhamadazmy**
[LogController] debounce on failure to avoid busy loops

Summary:
Track "trials" to write logs to avoid getting stuck in a busy
loop. This is solved by introduction a counter that is incremented
on trial.

If counter is not zero, a delay is introduced before retyring

Fixes #2079

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2109).
* #2106
* __->__ #2109

### CODE REVIEW

File: crates/admin/src/cluster_controller/logs_controller.rs [hunk 1]
```diff
@@ -925,28 +952,36 @@ impl LogsController {
...
         let tc = task_center().clone();
         let metadata_store_client = self.metadata_store_client.clone();
         let metadata_writer = self.metadata_writer.clone();
+        let debounce_delay = self.debounce_delay;
 
         self.async_operations.spawn(async move {
             tc.run_in_scope("logs-controller-write-logs", None, async {
+                if trial > TrialCounter::OLDEST {
+                    // add some delay to avoid busy loops
+                    tokio::time::sleep(debounce_delay).await;
```
Comment (pcholakov) [inline crates/admin/src/cluster_controller/logs_controller.rs:982]: Is this something we could use a `RetryPolicy` for? It has multiple benefits:

- will retry quickly at first, which will better mask short-lived transient failures
- backs off and slows down on continued unavailability
- introduces some stochastic randomness in the process which is a huge win when you have multiple instances of a component that might be attempting conflicting actions

File: crates/admin/src/cluster_controller/logs_controller.rs [hunk 2]
```diff
@@ -445,18 +446,33 @@ impl TryFrom<&LogletConfig> for LogletConfiguration {
     }
 }
 
+#[derive(
+    Default, Eq, PartialEq, PartialOrd, Ord, Clone, Copy, derive_more::From, derive_more::Into,
+)]
+struct TrialCounter(u8);
```
Comment (pcholakov) [inline crates/admin/src/cluster_controller/logs_controller.rs:452]: Minor nit but could we may be use `Attempt(s)Counter` to just to align terminology with `RetryPolicy`?

File: crates/admin/src/cluster_controller/logs_controller.rs (hunk 1 above)
Comment (muhamadazmy) [reply crates/admin/src/cluster_controller/logs_controller.rs:982]: Yeah, i was also considering the same, will do :)

File: crates/types/src/config/admin.rs [hunk 3]
```diff
@@ -64,6 +65,12 @@ pub struct AdminOptions {
     /// The default replication strategy to be used by the cluster controller to schedule partition
     /// processors.
     pub default_replication_strategy: ReplicationStrategy,
+
+    /// # Log Controller error retry policy
+    ///
+    /// The retry policy for log controller when it has
+    /// issue committing a reconfiguration
+    pub log_controller_error_retry_policy: RetryPolicy,
```
Comment (pcholakov) [inline crates/types/src/config/admin.rs:73]: I'd probably hard-code this for the time being, to avoid adding extra public config keys until we're sure we know what we want them to be :-) At least that's the approach we've taken in a few other places. I think the 15s default is sane for this purpose.

File: crates/admin/src/cluster_controller/logs_controller.rs [hunk 4]
```diff
@@ -494,18 +498,39 @@ impl TryFrom<&LogletConfig> for LogletConfiguration {
     }
 }
 
+#[derive(
+    Default, Eq, PartialEq, PartialOrd, Ord, Clone, Copy, derive_more::From, derive_more::Into,
+)]
+struct AttemptsCounter(u8);
+
+impl AttemptsCounter {
+    const OLDEST: AttemptsCounter = AttemptsCounter(0);
```
Comment (pcholakov) [inline crates/admin/src/cluster_controller/logs_controller.rs:507]: This caught my eye on the first pass but I didn't have a better idea - I find `OLDEST` slightly ambiguous here; maybe `EARLIEST` or `INITIAL` makes more sense. Only if you agree, whatever you decide is best.

**Review by pcholakov — APPROVED** [review]

File: crates/admin/src/cluster_controller/logs_controller.rs (hunk 4 above)
Comment (muhamadazmy) [reply crates/admin/src/cluster_controller/logs_controller.rs:507]: You are right. I will rename it. I think `FIRST` is better name in this context

File: crates/admin/src/cluster_controller/service.rs [hunk 5]
```diff
@@ -305,6 +307,14 @@ impl<T: TransportConnect> Service<T> {
                         warn!("Could not trim the logs. This can lead to increased disk usage: {err}");
                     }
                 }
+                Ok(_) = tail_udpates_watcher.changed() => {
+                    // we clone here to avoid holding the read lock in the watcher
+                    // more than necessary.
+                    // todo(azmy): do we really need to keep the updates inside an Arc?
+                    // the on_logs_tail_updates should return quick enough.
```
Comment (pcholakov) [inline crates/admin/src/cluster_controller/service.rs:314]: I guess the argument is to be more defensive and keep the `Arc` - even if we documented the requirement to keep the borrow lifetime short, it would be easy to miss making changes to faraway code in the future. Seems worth the cost/benefit tradeoff to me to add a comment why we did it this way, and keep as-is?

**Review by pcholakov — COMMENTED** [review]
I might be missing some fine detail but this looks good to me. The only caveat I still have is whether this is cheap enough to do at the heartbeat interval, or if we could slow it down a bit.

File: crates/admin/src/cluster_controller/logs_controller.rs [hunk 6]
```diff
@@ -954,13 +1018,24 @@ impl LogsController {
...
         self.async_operations.spawn(async move {
             tc.run_in_scope("logs-controller-seal-log", None, async {
+                if attempt > AttemptsCounter::FIRST {
+                    let delay = retry_policy
+                        .iter()
+                        .nth(usize::from(attempt) - 1)
+                        .unwrap_or(FALLBACK_MAX_RETRY_DELAY);
+                    tracing::debug!(?delay, %attempt, %log_id, %segment_index, "Wait before attempting to seal log");
+                    tokio::time::sleep(delay).await;
+                }
```
Comment (tillrohrmann) [inline crates/admin/src/cluster_controller/logs_controller.rs:1037]: Instead of creating a new retry_policy iterator on every attempt and then finding the right iterator entry, could we pass an `Option<RetryIter<'static>>` along? That way, we capture the attempt and also directly the next delay. `None` would mean no delay.

**Review by tillrohrmann — COMMENTED** [review]
Thanks for debouncing the retry attempts by the LogsController @muhamadazmy. The change for introducing the delays in the async task, is a good idea. I was wondering whether we could pass directly a `RetryIter<'static>` instead of reconstructing it on every attempt?

File: crates/admin/src/cluster_controller/logs_controller.rs (hunk 6 above)
Comment (muhamadazmy) [reply crates/admin/src/cluster_controller/logs_controller.rs:1037]: Yeah, that's definitely a better approach.

**Review by tillrohrmann — APPROVED** [review]
Really nice work @muhamadazmy. Thanks for fixing the potential for busy looping. LGTM. +1 for merging :-)
