### PR TITLE
[Bifrost] BackgroundAppender respects record-size-limit when cutting batches

### LINKED ISSUE #4132: Make Bifrost batching aware of message size limits
For some loglets (e.g. the replicated loglet) we have limits on how large batches of messages can be. Otherwise, the replicated loglet fails replicating them. We should make the batching logic aware of those potential limits so that we don't create batches that exceed this limit and thereby are no longer possible to successfully store the batched messages.

### PR DESCRIPTION
**Pull request by AhmedSoliman**
Previously, BackgroundAppender used recv_many() to batch records by count
only (max_batch_size). This change adds byte-size awareness to batch cutting,
ensuring batches do not exceed the configured record_size_limit.

Closes #4132

Changes:
- Introduce Batch struct to track accumulated bytes alongside operations
- Add AppendOperation::cost_in_bytes() to calculate record sizes
- Replace recv_many() with recv()/try_recv() loop that checks both byte
  and count limits before adding to batch
- Flush batch when adding a new operation would exceed limits
- Use cancellation_token() instead of cancellation_watcher() for drain

The batch is cut when either:
- Adding the next record would exceed batch_limit_bytes
- The batch reaches max_batch_size count

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/4144).
* __->__ #4144
* #4141
* #4140
* #4139

### CODE REVIEW

File: crates/bifrost/src/bifrost.rs [hunk 1]
```diff
@@ -1392,4 +1392,52 @@ mod tests {
...
+            }
+        }
+
+        assert_that!(enqueued, eq(100));
+
+        // Wait for all to be committed
+        let token = sender.notify_committed().await?;
+        token.await?;
+
+        handle.drain().await?;
```
Comment (tillrohrmann) [inline crates/bifrost/src/bifrost.rs:1433]: Is this important for the below assertion to succeed? Or would it be enought to await the `token` and then to the `find_tail` operation?

Comment (AhmedSoliman) [reply crates/bifrost/src/bifrost.rs:1433]: it's superfluous.
