### PR TITLE
Show invocation completion in CLI

### LINKED ISSUE #1712: `TerminalError` / `TerminalException` could output with more details in the cli
Hi 👋, first thanks for your work on restate and what's coming!

Might be an idea to output a `TerminalError` with the status `completed` and with `Error` / `Caused by` and even the `Trace ID` ?

Cause atm, there's no UI diff between a successful completed inv / an inv that has been terminated with a `TerminalError`

e.g with this simple workflow:
```ts
export const throwableWorkflow = workflow({
  name: "throwable",
  handlers: {
    run: async (ctx: WorkflowContext) => {
      throw new TerminalError("Should show up in the restate cli?", { errorCode: 500 })
    },
  },
})
```
CleanShot 2024-07-10 at 15 25 31@2x

Thanks!

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #1712

Using restate 1.0:

```
  ❯ [2024-07-18 09:22:21.760 +02:00] inv_1eQGNqArQ5Hz78SmQy5dvDqYgj7lxjQp1L
     Target:      WorkflowTest/c/run                                                
     Status:      backing-off  (12 minutes, 21 seconds and 606 ms. Retried   
                  66 time(s). Next retry in in 7 seconds and 134 ms))        
     Deployment:  id: dp_13sgmJ9OIJWO79hTDuusMQF, service protocol version: 1       
                  [ZOMBIE] using restate-sdk-java/1.1.0-SNAPSHOT_fbfb16cc 
     Error:       [2024-07-18 09:34:39.353 +02:00]                            
                  [500] error trying to connect: tcp connect error: Connection  
                  refused (os error 111)                                         
     Caused by:   UNKNOWN                                                           

  ❯ [2024-07-18 09:21:55.534 +02:00] inv_174rq2A9bm3T5ULE0nBRhDSHXY9sW3YBk5
     Target:  WorkflowTest/b/run 
     Status:  completed   

  ❯ [2024-07-18 09:21:10.097 +02:00] inv_1dceKvwtEc2n1psdzgswxMZsRxdZ6x5unf
     Target:  WorkflowTest/a/run 
     Status:  completed  
```

Using this branch:

Screenshot from 2024-07-18 09-37-16

### CODE REVIEW

File: cli/src/clients/datafusion_http_client.rs [hunk 1]
```diff
@@ -133,6 +134,24 @@ impl DataFusionHttpClient {
...
+                table_name = '{table}'
+                AND column_name IN ({})",
+                columns.iter().map(|s| format!("'{s}'")).join(", ")
+            ))
+            .await?;
+
+        Ok(actual_count as usize == expected_count)
+    }
+
+    // check if column exists: SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'sys_invocation' AND column_name IN ('completion_result', 'completion_failure')
```
Comment (tillrohrmann) [inline cli/src/clients/datafusion_http_client.rs:154]: Do we want to keep it?

**Review by tillrohrmann — APPROVED** [review]
Nice improvement @slinkydeveloper. LGTM. +1 for merging.
